name: CI Release

on:
  release:
    types: [published]

env:
  PROJECT_FILE: FunWithGithubActions/FunWithGithubActions.csproj
  PROEJCT_PREFIX: "Fun With GitHub Actions"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        kind: ['linux', 'windows']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build
      run: dotnet publish "${{ PROJECT_FILE }}" -c Release -r "${{ matrix.target }}"  -f netcoreapp3.1 |
        -o "${{ PROEJCT_PREFIX }}-${{ github.event.release.tag_name }}-${{ matrix.target }}" /p:Version=${{ github.event.release.tag_name }}
